### PR TITLE
Check for null inputs in isFeatureEnabled

### PR DESCRIPTION
**Pull request by mjc1283**

### CODE REVIEW

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by wangjoshuah** [comment]
build

**Comment by mikeng13** [comment]
build

**Pull request merged**
