### PR TITLE
Introduce v3 batch event endpoint to Node SDK

### PR DESCRIPTION
**Pull request by mauerbac**

### CODE REVIEW

**Comment by caitlinrubin-optimizely** [comment]
test this please

**Comment by mikeng13** [comment]
test this please

**Comment by mikeng13** [comment]
test this please

**Comment by mikeng13** [comment]
ok to test

**Comment by caitlinrubin-optimizely** [comment]
retest this please

**Comment by mikeng13** [comment]
I ran the e2e test manually and it looks good. Gonna merge it in.

**Pull request merged**
