### PR TITLE
1.5.0 bump

### PR DESCRIPTION
**Pull request by alda-optimizely**

### CODE REVIEW

**Comment by mikeng13** [comment]
build

**Comment by mikeng13** [comment]
lgtm

**Comment by aliabbasrizvi** [comment]
You also need to update revision here: https://github.com/optimizely/node-sdk/blob/master/package.json

**Comment by alda-optimizely** [comment]
I've updated the package.json in a new diff: https://github.com/optimizely/node-sdk/pull/101

**Pull request merged**
